# É preciso criar o PV correspondente para cada réplica
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1 # 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: examplepassword
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: meu-pvc
          mountPath: /var/lib/mysql  # Onde os dados serão armazenados no container
  volumeClaimTemplates:
  - metadata:
      name: meu-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi