# Antes de aplicar esse manifesto é preciso criar o certificado e a chave privada com os seguintes comandos:
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout chave-private.key -out certificado.crt 
# Antes de aplicar esse manifesto ainda é preciso criar o Secret usando os arquivos criados com o comando:
# kubectl create secret tls meu-servico-web-tls-secret --cert=certificado.crt --key=chave-private.key 
# Antes de aplicar esse manifesto também é preciso que tenha sido criado o arquivo de configuração do nginx (nginx.conf)
# e também o ConfigMap nginx-config através do comando: 
# kubectl get configmap nginx-config -o yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: nginx-tls
      mountPath: /etc/nginx/tls
  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-config
    - name: nginx-tls
      secret:
        secretName: meu-servico-web-tls-secret
        items:
          - key: certificado.crt
            path: certificado.crt
          - key: chave-privada.key
            path: chave-privada.key