# Aplique o manifesto example-secret.yaml primeiro
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: example-secret  # Secret que você criou previamente
          key: username         # data do Secret que você criou previamente
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: example-secret  # Secret que você criou previamente
          key: password         # data do Secret que você criou previamente