# Primeiro é preciso executar o manifesto headless-svc.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx        # Tem que ser igual a .spec.template.metadata.Labels
  serviceName: "nginx"
  replicas: 1           # Por padrão é 0 (zero)
  minReadySeconds: 10   # Por padrão é 0 (zero)
  template:
    metadata:
      labels:
        app: nginx      # Tem que ser igual a .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
