apiVersion: v1
kind: Pod
metadata:
  name: secret-test-env
spec:
  containers:
  - name: env-test-container
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-test
          key: username
