# Aplicar esse manifesto primeiro
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi # Tamanho do armazenamento (1 GiB)
  accessModes:
    - ReadWriteMany # Modo de acesso (leitura/escrita por um único Pod ???)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/dados # Caminho no host onde os dados serão armazenados
